[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
log = "0.4.22"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
simple-logging = "2.0.2"
